name: CI

on:
  push:
    branches: [main]
    paths: [argh/**, examples/**]
  pull_request:
    branches: [main]
    paths: [argh/**, examples/**]

permissions:
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - run: make check
      - run: make lint

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Run tests
        run: cargo nextest run --lib --profile ci

      - name: Test report
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Test Results
          path: target/nextest/ci/junit.xml
          reporter: java-junit

      - run: make build
