name: Build & Deploy Site

on:
  push:
    branches: [main]
    paths: [argh/**]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack

      - run: make doc
      - run: echo '<meta http-equiv="refresh" content="0;url=argh/index.html">' > target/doc/index.html
      - run: |
          mkdir site
          cp -r target/doc/ site/
          cp misc/pages-index.html site/index.html

      - run: |
          make wasm-build
          mkdir -p site/examples/web_wasm
          cp -r examples/web_wasm/pkg site/examples/web_wasm/
          cp examples/web_wasm/index.html site/examples/web_wasm/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - uses: actions/deploy-pages@v5
