name: Build & Deploy Site

on:
  push:
    branches: [main]
    paths: ["argh/**", "examples/**", ".github/workflows/pages.yml"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack

      - run: make site

      - uses: actions/upload-pages-artifact@v5
        with:
          path: site

      - uses: actions/deploy-pages@v5
